### PR TITLE
install and use a global audioLogger instead of Serial

### PR DESCRIPTION
**Pull request by d-a-v**

### CODE REVIEW

**Comment by earlephilhower** [comment]
Is there some way to silence it using the new logging infrastructure?

**Comment by d-a-v** [comment]
I use this class but here we need only a similar `FakePrint` class.
I will add one to the PR as an option, to make it consistent.

```
#ifndef FAKESTREAM_H
#define FAKESTREAM_H

class FakeStream: public Stream
{
protected:
        size_t fakesize;

public:
        FakeStream (size_t size): fakesize(size) { }
    
        virtual int available() { return fakesize; }
        virtual int read() { if (fakesize) { --fakesize; return 0x5a; } return -1; }
        virtual int peek() { return fakesize? 0x5a: -1; }
        virtual void flush() { fakesize = 0; };
        virtual size_t write (uint8_t data) { (void)data; return 1; }
        size_t size () { return fakesize; }
        const char* name () { return "Fake"; }
};

#endif // FAKESTREAM_H
```

**Comment by d-a-v** [comment]
Since this is a breaking change, would you prefer
- to stay with &Serial by default
- to update examples to initialize `audioLogger` to `&Serial` ?

**Comment by earlephilhower** [comment]
Cool, thanks. I'm traveling today but will try and look at it tonight.

**Comment by FatherMarco1971** [comment]
I'm not so expert so please forgive if i can't propose a solution or if my comment is not correct. This audiologger is a little bit strange i think: why is still present the line Serial.Flush() here and there in the code?
` if (!buff || !outSample) {
    audioLogger->printf_P(PSTR("ERROR: Out of memory in AAC\n"));
    Serial.flush();
`
 
More to this if i don't initialize audiologger I was expecting to stop seeing messages from serial but this doesn't happen, could be an error in the commit (https://github.com/earlephilhower/ESP8266Audio/pull/198/commits/3a23ccaa48370e4bc3413610c07a096eb1e63364)?

**Pull request merged**
