### PR TITLE
Fix build support gcc8 for other arch

### PR DESCRIPTION
**Pull request by shuai132**
See: https://github.com/earlephilhower/ESP8266Audio/pull/502

Tested on `toolchain-riscv32-esp @ 8.4.0+2021r2-patch3`

### CODE REVIEW

**Review by earlephilhower — APPROVED** [review]
Thanks!

**Comment by earlephilhower** [comment]
@shuai132 the ESP32 build is still busted with a GCC bug:
````
In file included from /home/runner/work/ESP8266Audio/ESP8266Audio/libraries/ESP8266Audio/src/AudioGeneratorMIDI.cpp:69:
/home/runner/work/ESP8266Audio/ESP8266Audio/libraries/ESP8266Audio/src/libtinysoundfont/tsf.h: In function 'void tsf_channel_midi_control(tsf*, int, int, int)':
/home/runner/work/ESP8266Audio/ESP8266Audio/libraries/ESP8266Audio/src/libtinysoundfont/tsf.h:2101:1: error: insn does not satisfy its constraints:
 }
 ^
(insn 858 342 343 51 (set (reg:SF 19 f0 [407])
        (mem/u/c:SF (symbol_ref/u:SI ("*.LC248") [flags 0x2]) [0  S4 A32])) "/home/runner/work/ESP8266Audio/ESP8266Audio/libraries/ESP8266Audio/src/libtinysoundfont/tsf.h":2054 47 {movsf_internal}
     (nil))
during RTL pass: postreload
````

Can you add a check for XTENSA to the condition, instead of looking the the patch level?  Like:
````
#if (__GNUC__ == 8) && defined(__XTENSA__)
````

**Comment by shuai132** [comment]
@earlephilhower Good idea,
I just tested on ESP32C3 toolchain before, which is 10.x.

And my esp32 toolchain(maybe latest) seems still 8.x:
```
echo | ./xtensa-esp32-elf-gcc -dM -E - | grep GNU
#define __GNUC_PATCHLEVEL__ 0
#define __GNUC__ 8
#define __GNUC_STDC_INLINE__ 1
#define __GNUC_MINOR__ 4
```

**Comment by shuai132** [comment]
Thanks, risc-v gcc 8.4 works now!
```
➜  ./riscv32-esp-elf-gcc --version
riscv32-esp-elf-gcc (crosstool-NG esp-2021r2-patch3) 8.4.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Pull request merged**
