### PR TITLE
Porting for ESP-32

### PR DESCRIPTION
**Pull request by tueddy**
This is my initial port for compile on ESP-32.
This is currently working:
- Play wav on I2S DAC

I was unable to port the libmad MP3 decoder..
For testing i deleted the libmad folder and used the libmad from
https://github.com/MrBuddyCasino/ESP32_MP3_Decoder/tree/master/components/mad

Best Dirk

### CODE REVIEW

**Comment by earlephilhower** [comment]
I gave it a once-over this morning and it looks great.  Real shame about the silly WiFi header name differences.  Let me pull it down and do a few 8266 tests while reading it a bit deeper later this week/weekend.

Also, can you do a git add on the libmad-esp32?  I'm actually quite surprised it works because I changed some of the APIs on the 8266 version to reduce memory footprint...

**Comment by tueddy** [comment]
Hi,

i've added libmad-esp32 to my forked reposity. Should i do a new PR? You can find it here
https://github.com/tueddy/ESP8266Audio/tree/master/src/mad-esp32

This compiles for ESP32 if i uncomment some functions in AudioGeneratorMP3.cpp but crashes on device later. 
As far as i can see the mp3 decoding loop has to be in separate task/thread? Also see this working implementation:
https://github.com/MrBuddyCasino/ESP32_MP3_Decoder/blob/master/components/mp3_decoder/mp3_decoder.c

Sorry the MP3 decoding part is a bit beyond my knowledge.. 
Best Dirk

**Comment by earlephilhower** [comment]
No need for new PR, when you push a new commit to a branch it gets grabbed automatically.

No worries on the MP3 stuff.  With the MP3 libs you just added, I assume it still isn't quite working, no?  We can have a partial setup at least...and on AAC you have enough RAM for SSB, which lets the ESP32 handle all online audio AAC webcasts!

**Comment by tueddy** [comment]
Ah i see, github is great for that! Just comitted the files..

For my test i used PlayMP3FromSPIFFS.ino and had to uncommented the stack methods at the end of AudioGeneratorMP3.cpp.
Then i got
AudioGeneratorMP3.cpp:149:51: error: 'struct mad_pcm' has no member named 'samples'
AudioGeneratorMP3.cpp:140:61: error: 'mad_synth_frame_onens' was not declared in this scope

After comment out i can compile, this is the debug output on ESP-32 device:
Sample MP3 playback begins...
ID3 callback for: Title = 'Piano Sample'
ID3 callback for: Performer = 'Artist Goes Here'
ID3 callback for: Album = 'Album Goes Here'
ID3 callback for: Year = '2010'
Guru Meditation Error: Core  1 panic'ed (Unhandled debug exception)
Debug exception reason: Stack canary watchpoint triggered (loopTask) 
Rebooting...

OK this can't work but seems a starting point?

**Comment by earlephilhower** [comment]
Great news!

I got around to unwrapping my ESP32 and installing the Arduino IDE tonight.  First up, "Blink!" Which, of course doesn't compile out of the box  D'oh!  Anyway, simple fix and I then moved to the Audio stuff.

MP3 decoding is now working using the original ESP8266 code.  About 10 lines changed in the code was all it took.  Here's my speed test app I use to play from PROGMEM:
````
rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:956
load:0x40078000,len:0
load:0x40078000,len:13076
entry 0x40078a58
Free mem: 222540
Free mem: 192196
mp3 begin

791445679 cycles
836 loops
MP3 done
Free mem: 192196
````

We don't need or want the mad-esp32 lib you included in the latest patch, it's only for non-os and has some weird stuff going on.

So, if you could please
````
git rm -r mad-esp32
````
Then apply the patch I'm going to attach below
````
patch -p1 < file.patch
````

Then build an MP3 example, git commit, and re-push it up I think we'll be golden!

There are some warnings that need to be addressed, but let's get this working first then optimize later.

**Comment by earlephilhower** [comment]
If it's a problem, I can accept this PR and then do the patch changes.  But since you did the work I want to make sure you get a chance to put it in yourself, first.  Just let me know!

**Comment by tueddy** [comment]
Wow, that seems to work!
I have have to test on real I2S DAC later today, but software runs fine on my naked ESP8266/ESP32 devices!
Code cleanup and optimization can be done now with working code, thank you very much! 
Now i can go on with my kids-player project and have more hardware choices..
Dirk

**Comment by earlephilhower** [comment]
Thanks for the contribution!  I just fixed the two compiler warnings and enabled the audio PLL for playback.  Pull the new tree and give it a go.

**Comment by reaper7** [comment]
esp32 does not have WiFi.hostname
it causes error
try to add:
```
#ifdef ESP32
  WiFi.setHostname("melody");
#else
  WiFi.hostname("melody");
#endif
```

**Comment by earlephilhower** [comment]
I'm looking into getting Travis-CI to build the code and all examples on an ESP8266 and an ESP32 toolchain to catch things like this.  Right now the examples probably have a few more issues like this, but the core audio playback libs seem clean enough (build-wise).

**Comment by reaper7** [comment]
output (noADC option) for webradio -> only squeaks like a bunch of bats ;)
I try this on m5stack (esp32) where speaker is connected to DAC pin gpio25

**Comment by earlephilhower** [comment]
Just updated the examples.

Want to open a new issue for this, @reaper7 ?  I don't have a DAC or output connected to my ESP32 yet (I've wirewrapped my only I2S DAC to the ESP8266) but I believe @tueddy has tried a few examples and gotten sound.  I get Brownouts whenever I enable WiFi that I need to debug (powered USB hub required?) before I can try the web samples.

If you could try and pinpoint if some examples work or don't, that would help immensely, too.  

Thx!

**Comment by earlephilhower** [comment]
The internal DAC is not being used with the current I2S code.  I'll probably add either a method or a new class for this, but for now what you need to hook up the 1-T amplifier to is specified here.  (I think I can do better SNR than the built-in dac....64x oversampling @ 44KHZ is >10 bits resolution, and that should be easy to run @240MHz).
````
i2s_pin_config_t pin_config_dac = {
    .bck_io_num = 26, //this is BCK pin
    .ws_io_num = 25, // this is LRCK pin
    .data_out_num = 22, // this is DATA output pin
    .data_in_num = -1   //Not used
};
````
So, pin 22 is the pin you want to try out as-coded.  This will also be configurable at some time.

**Comment by reaper7** [comment]
clear :)
I hoped it would work on m5stack with builtin speaker & amp + separated power supply for this...
so, I will be waiting :)

**Comment by tueddy** [comment]
Hi,
AudioOutputI2SDAC : my external DAC runs fine on the pins above, so yes DOUT is 22. 

AudioOutputI2SNoDAC: I get scrambled output, so somethings is still wrong.
I think i2s_set_pin should be initialized with Null to enable internal DAC like this:
i2s_set_pin((i2s_port_t)0, NULL);

Don't know if this is required:
   i2s_set_dac_mode(I2S_DAC_CHANNEL_BOTH_EN);

**Comment by earlephilhower** [comment]
I think there's some confusion about the DAC/NoDAC and how it relates to the ESP32.

On the ESP8266 there is no hardware DAC, so to simulate one I implement a software technique that's employed to digitally simulate one called a delta-sigma DAC (or sigma-delta if you like).  Basically it takes the requested voltage level and turns it into a random series of bits whose trailing average sum is the analog voltage you want to provide.  Pass this high frequency random bitstream through a LPF (or not in the simplest case), and amplify it and you have an analog output from a pure digital stream.  If you look at an audio amp and see "192x oversampling," we're doing the same thing here.

That's what I2SNoDAC does today.  Lots of math, output = random bits which are only intended to drive a digital amplifier/speaker directly.  It can NOT drive an I2S DAC or a hardware DAC, only an amplifier.

For the ESP32 you can still do the above (in fact, do it better than the ESP8266 since you have more CPU and can oversample and generate an effective 10-20 bits of resolution from 1 pin!).

The ESP32 also has a mode where you can drive the normal I2SDAC() bits (normal PCM samples) into a built-in 8-bit DAC (yuck) which then drives an analog output pin.  To do this, you need to use the I2SOutputDAC (*not* the I2SNoDAC) *plus* set the magic ESP control bit to say "route the I2s data to internal dac, not pin).

I'd need to look at the SDK to give the exact call, but I think you're on the right idea here, @tueddy .  One of those calls *after* starting the i2s->begin() should reroute the data from the I2SDAC() code to the onboard HW DAC to the analog output.  Once the magic incantation is there, I'll just have to add a method to set the pin and let it take either a pin num or "INTERNAL_DAC_(0|1)" and Bob's your uncle.

**Comment by tueddy** [comment]
OK, that was indeed confusing, i didn't thought about this.
I think there are two options now:
- Make a new audio output class "AudioOutputI2SInternalDAC_ESP32" and coexist with "AudioOutputI2SNoDAC"
- Use software DAC on ESP8266 and  internal DAC on ESP32 in "AudioOutputI2SNoDAC" 

I would prefer the second option. Use same class for both platforms so you can easily switch board without rewriting. What do you think?

**Comment by earlephilhower** [comment]
That seems backwards to me, because you really do have a DAC on the ESP32, and it needs unadulterated samples, just like an external one.

I'll need to cogitate on it a bit, but right now I think the right way forward is:
. Remove the global, hard coded i2s settings now #if ESP32'd.
. Add a constructor, #ifdef ESP32'd, I2SDAC::I2SDAC(<bclk>,<lrclk>,<dout>) => Set these as the I2S Pins
. Modify I2SDAC()::I2SDAC() to default to something sane on the ESP32 (existing settings?)
. Add a constructor, #ifdef ESP32, I2SDAC::I2SDAC(INTERNAL_DAC_[0|1] <a class enum>), which routes the I2S data to internal 8-bit DAC
.Modify I2SNoDac::I2SNODAC() to use sane defaulrs on ESP32
. Add a constructor, #ifdef ESP32'd, I2SNODAC::I2SNODAC(<bclk>,<lrclk>,<dout>) => Set these as the I2S Pins

This way if you just want any kind of noise w/o add'l hardware, you can use the I2SDAC(internal0).

If you want higher quality w/o including a real I2SDAC on your board, then use the I2SNoDac with 64x or 128x oversampling (which, believe it or not, should have way better SNR than the onboard DAC....almost all commercial high-perf DACs use delta-sigma because doing a DAC is a massively hard analog problem for a digital chip). 

And if you can spring for it, you can still use the original I2S interface with a real high-quality I2S external DAC chip.

**Comment by tueddy** [comment]
That "sound"'s like the right way..
Anywhere i will use external DAC, hardware is needed in my project because of the amplifier.
I'll test latest commit's now and give you feedback,
best Dirk

**Pull request merged**
