### PR TITLE
add PDM mode for ESP32

### PR DESCRIPTION
**Pull request by reaper7**

### CODE REVIEW

**Comment by earlephilhower** [comment]
Thanks!  I'll look into this over the weekend.  Been hacking I2S input stuff on the ESP8266 and it's hard to context switch...

**Comment by earlephilhower** [comment]
Looks nice and clean!  How does the PDM sound?  I assume it's about the same as the SW I2SDAC since it's implementing the same logic, but I've no idea the oversampling they're implemented.

**Comment by reaper7** [comment]
Hm...I was expecting a better sound.
I checked it only on M5Stack built-in speaker
but with the same conditions, internal DAC at low gain 0.1... 0.9 sounds cleaner, PDM contains a lot of white noise.
Maybe it's a weak m5stack amplifier but it is not audible when DAC mode is selected.
I need to check it out on the external amplifier and better speakers.

**Comment by earlephilhower** [comment]
Wouldn't be the first part of the chip to be a little flaky. :(  If you do get to hooking up an external amp and speaker, can you also try the I2SNoDAC software DAC?  I'd like to know what to recommend folks use on the ESP32.  On the 8266, the SW DAC is pretty good sounding w/ a 1-T "amp" and $0.50 speaker.

The other thing is that you can't use a regular amp on PDM output.  The output is always either 0 or 3.3V, and intended to drive a FET-type digital amp.  If you feed it into a regular Op-Amp input it'll do bad things, depending on the frequency response.  You may be able to fudge it by doing an analog LPF network on the output pin before the analog amp's input, but the cutoff parameters will need to match the oversampling rate (which is pushing noise up in frequency...which will alias down w/o this LPF).

**Comment by reaper7** [comment]
> The other thing is that you can't use a regular amp on PDM output. The output is always either 0 or 3.3V, and intended to drive a FET-type digital amp.
Maybe for this reason PDM on M5Stack(with simply class D amp NS4148) sounds distorted (gain==1.0) and generates a lot of noise on lower gain.
I will check this asap.

**Pull request merged**
