### PR TITLE
Initial SPIRAM buffer support

### PR DESCRIPTION
**Pull request by armSeb**
Here is the code for supporting buffer in SPI RAM.

### CODE REVIEW

**Comment by earlephilhower** [comment]
For some reason GitHub isn't sending me emails anymore, so I didn't notice until this AM. 

Couple things I noticed:
. The new files are yours, so please do replace my (C) with yours (C) in their headers.
. For SPIRAM, we'll just wait until your PR is merged and then delete the local copies in this pull, right?

OTW looking good!

**Comment by earlephilhower** [comment]
Looks good!  When your SPIRAM library PR is merged, I'll merge this and we'll be all set.

**Comment by earlephilhower** [comment]
Would it also make sense to include the circuit diagram you're using to hook up the RAM chip, or is there only one way it could go and therefore obvious?  The main README.md would be a good spot for this, I think.

**Comment by armSeb** [comment]
It's already on my TOTO list ;)

**Comment by armSeb** [comment]
Hello, I finally added the schematic. Please let me know if I need to change something ;)

Seb.

**Comment by earlephilhower** [comment]
Just merged it all in.  Thanks for sharing!

**Pull request merged**
